class Config:
  HOME = "C:\\Altairix"
  WORKSPACE = HOME + "\\Workspace\\Oxygen\\Brainex"

  GIT_REPO = HOME + "\\Git Repository"
  ADF_REPO = GIT_REPO + "\\ADF"
  ADF_COMMON = ADF_REPO + "\\Altairix ADF - Common\\src"
  ADF_SERVER = ADF_REPO + "\\Altairix ADF - Server\\src"
  ADF_SYNC = ADF_REPO + "\\Altairix ADF - Sync\\src"
  ADF_ASYNC = ADF_REPO + "\\Altairix ADF - Async\\src"
  ADF_GWT = ADF_REPO + "\\Altairix ADF - GWT\\src"
  BX_REPO = GIT_REPO + "\\Brainex"
  BX_COMMON = BX_REPO + "\\Arrowsmith - Common\\src"
  BX_SERVER = BX_REPO + "\\Arrowsmith - Server\\src"
  BX_SYNC = BX_REPO + "\\Arrowsmith - Sync\\src"
  BX_ASYNC = BX_REPO + "\\Arrowsmith - Async\\src"
  BX_GWT = BX_REPO + "\\Arrowsmith - GWT\\src"
  LOCAL_REPO = GIT_REPO + "\\Brainex-Local"

  JS_TRACK = "webAssess-think"
  JS_DEV_TRACK = "develop"
